### ISSUE TITLE
[V1] Switch icon strategy to Iconify

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#294]
## Context

Right now, two different strategies are used in the codebase:

- [phosphor icon set](https://phosphoricons.com/), rendered as SVG-in-CSS via the [phosphor-icon-tailwindcss](https://github.com/vnphanquang/phosphor-icons-tailwindcss) plugin,
- [simpleicon icon set](https://simpleicons.org/), rendered as inline SVG via the [@svelte-put/inline-svg](https://svelte-put.vnphanquang.com/docs/inline-svg) package (preprocessor strategy)

As for the simple icon set, we have to add to the repo each icon as needed. Assets also duplicate if used in multiple places. Together, this unnecessarily complicates the setup. Let's switch to [iconify](https://iconify.design/docs/usage/css/tailwind/tailwind4/) for a more unified and minimal solution.

## Approach

Remove `phosphor-icon-tailwindcss` and `@svelte-put/inline-svg` if not used elsewhere. Install the necessary packages:

```bash
pnpm add -D @iconify-json/ph @iconify-json/simple-icons @iconify/tailwind4
```

Load the iconify tailwind plugin with the following config:

```css
@plugin '@iconify/tailwind4' {
	prefix: i;
	override-only: true;
}
```

Include a custom Tailwind utility for the base icon style:

```css
@utility i {
  @layer components {
     display: inline-block;
     width: 1em;
     height: 1em;
     background-color: currentcolor;
     color: inherit;
     mask-image: var(--svg);
     mask-size: 100% 100%;
     mask-repeat: no-repeat
  }
}
```

Finally, refactor all usage of `i-[...]` and `inline-src`. Remember to check for CSS usage of the `--icon-url` property too. Use [iconify search](https://icon-sets.iconify.design/) to find the correct name for the icon.
